// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WPFGameShop
{
    public partial class Discount
    {
        [Key]
        public int GameId { get; set; }
        public int Percantage { get; set; }
    }
}