// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace WPFGameShop
{
    public partial class GameshopContext : DbContext
    {

        readonly string connectionString = @"Data Source=.\SQLEXPRESS;Trusted_Connection=Yes;DataBase=GameShop;";
        public GameshopContext()
        {
        }

        public GameshopContext(DbContextOptions<GameshopContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<EarlyAccesGame> EarlyAccesGame { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GameGenre> GameGenre { get; set; }
        public virtual DbSet<GameView> GameView { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS");

            modelBuilder.Entity<Discount>(entity =>
            {
                entity.HasKey(e => e.GameId)
                    .HasName("PK_Sale");
            });

            modelBuilder.Entity<EarlyAccesGame>(entity =>
            {
                entity.Property(e => e.GameId).ValueGeneratedNever();
            });

            modelBuilder.Entity<GameView>(entity =>
            {
                entity.ToView("GameView");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);


            optionsBuilder.UseSqlServer(connectionString);
        }
    }
}