// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WPFGameShop
{
    [Keyless]
    public partial class GameView
    {
        [Required]
        [StringLength(20)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }
        public int Id { get; set; }
        [Required]
        [Column(TypeName = "image")]
        public byte[] Cover { get; set; }
        [Column(TypeName = "money")]
        public decimal Price { get; set; }
        public int Rating { get; set; }
        public bool? IsEarlyAccess { get; set; }
        public int Discount { get; set; }
    }
}