// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WPFGameShop
{
    [Keyless]
    public partial class GameGenre
    {
        [Column("GameID")]
        public int GameId { get; set; }
        [Column("GenreID")]
        public int GenreId { get; set; }
    }
}